approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 5d

npmPreapprovedPackages:
  - "@open-mercato/*"

npmScopes:
  open-mercato:
    npmMinimalAgeGate: 0
    npmRegistryServer: "https://registry.npmjs.org"
